[package]
name = "blub"
version = "0.1.0"
authors = ["Jason Harris <sirmanlypowers@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "pow2"
#name = "cos"
harness = false
